[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  framework = "#static"
  port = 8888

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"

[functions."api"]
  included_files = ["netlify/lib/**"]
